### PR TITLE
Replace antlr3 parsers with bison/flex

### LINKED ISSUE #1388: Crashes on openwrt
I build owntone on openwrt(x86-64 platform). It crashes every time while opening the webpage. I find that it crashes when the client requests "/api/library/count?expression=....". No problem occurs if the request is just "/api/library/count".
It is related to the latest musl version(1.2.2) openwrt toolchain uses. It is unknown if there are any other similar problems. Using musl 1.1.24 everything seems to work fine.
This happens from version 27.4 to 28.2, and other versions are not tested. So any idea to solve this problem?
[log.txt](https://github.com/owntone/owntone-server/files/7858949/log.txt)

### PR DESCRIPTION
**Pull request by ejurgensen**
Replacing the antlr parsers solves multiple issues:

- Build warnings (issue #307)
- Build hacks: "-Xconversiontimeout 30000" and other Makefile magic
- Incorrect parsing of daap queries with sql wildcards (like 'tag:*tes%t_ng*')
- Infinite recursion/memory/CPU (issue #570 and #1248)
- systemd service file workarounds due to memory/CPU issue
- ANTLR3 being replaced with ANTLR4 (that doesn't support C file generation)
- Runtime dependency on antlr library
- Difficult installs of ANTLR3 on some systems (special install script)
- libantlr3c crash on OpenWrt (resolves #1388)

### CODE REVIEW

**Comment by ejurgensen** [comment]
@frankusb I am planning on replacing the current parsers in OwnTone, and a tricky one is the RSP query parser. To replace that, I need some test data, so the RSP requests that a Soundbridge would make. Then I can run them through the old parser and make sure the new parser acts the same. Since I don't have a device, I was thinking if you could help? It would be about making as many different requests to OwnTone as you can think of, and then grabbing them from the log (debug level required). It's only the requests that have a query parameter that are interesting. So like this one:
`RSP request: '/rsp/db/0/album?query=artist%3D%22David%20Bowie%22&type=browse'`

**Comment by frankusb** [comment]
Oh yes, of course.

I recently tried to compile owntone on a Dockstar and it failed due to java errors and antlr3 requires it indirectly.

I'm currently running 28.2, is this sufficient or do I need to be on HEAD?

**Comment by ejurgensen** [comment]
Sounds good, any version should be fine. And yes, I have also had trouble with antlr3 a number of times.

**Comment by frankusb** [comment]
I think I used every menu option in the attached log. Let me know if you need anything else.

[owntone.log](https://github.com/owntone/owntone-server/files/7866403/owntone.log)

**Comment by ejurgensen** [comment]
@frankusb thanks for the log. I don't know if it was on purpose, but it was great that you also included some "tricky" requests like the one where the title included some double quotes. I have now added a rsp parser to the branch. You are welcome to test, of course.

**Comment by frankusb** [comment]
I believe I have switched to it. I switched to the bison_parser1 branch, make, sudo make install, systemctl restart owntone for good measure and the Soundbridge seems fine. Is there a way to verify I am using the correct server binary?

I did find what I think might be a bug not related to Soundbridge.

All files for the artist "Weird Al" Yankovic show "Weird Al" Yankovic in the artist tag according to kid3 and I sampled two files with ffprobe. Yet in the web interface, all songs except Talk Soup show up under Weird Al Yankovic while Talk Soup shows up under "Weird Al" Yankovic.

Input #0, mp3, from '07-Talk Soup.mp3':
  Metadata:
    album           : Alapalooza
    artist          : "Weird Al" Yankovic
    genre           : Comedy
    title           : Talk Soup
    track           : 7
    date            : 1993
  Duration: 00:04:24.31, start: 0.025056, bitrate: 192 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : LAME3.93 
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 300x300 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other

Input #0, mp3, from '06-Traffic Jam.mp3':
  Metadata:
    album           : Alapalooza
    artist          : "Weird Al" Yankovic
    genre           : Comedy
    title           : Traffic Jam
    track           : 6
    date            : 1993
  Duration: 00:04:01.79, start: 0.025056, bitrate: 192 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : LAME3.93 
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 300x300 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other

**Comment by ejurgensen** [comment]
Thanks for testing so quickly. If the log is debug level you can check version by looking for ‘Trying RSP query’. It should *not* be present in the new version. 

The issue you observed is mysterious, and difficult to debug. I will get back to you with a suggestion.

**Comment by frankusb** [comment]
I don't think my test is valid then.

[2022-01-15 17:18:18] [DEBUG]      rsp: Trying RSP query -album_artist="2Cellos"-

**Comment by ejurgensen** [comment]
If you didn't give any configure flags (prefix etc.) then it is probably installed in /usr/local/sbin/owntone. This can practical, because it means you can have a "production" /usr/sbin/owntone (perhaps installed by your distro or via my RPi repo) and then /usr/local/sbin/owntone is a testing version.

In fact, if you already have owntone installed, you can just stop it and then run a test owntone straight from the build directory (./src/owntone). Then you don't need "make install".

Note that without configure flags owntone will look for a config file in /usr/local/etc/owntone.conf, so you can make a copy of your config there.

**Comment by ejurgensen** [comment]
With regard to the  "Weird Al" Yankovic issue, I can't figure out what might be causing it. My best suggestion is if you could send the two files + your songs3.db to me at espenjurgensen@gmail.com.

**Comment by frankusb** [comment]
> If you didn't give any configure flags (prefix etc.) then it is probably installed in /usr/local/sbin/owntone. This can practical, because it means you can have a "production" /usr/sbin/owntone (perhaps installed by your distro or via my RPi repo) and then /usr/local/sbin/owntone is a testing version.

I do have a prefix. --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-install-user --enable-chromecast --disable-spotify
/usr/local/sbin/owntone does not exist, only /usr/sbin/owntone. I don't think my distro (Debian) has owntone in it. I am on x64.

> In fact, if you already have owntone installed, you can just stop it and then run a test owntone straight from the build directory (./src/owntone). Then you don't need "make install".

I did not figure out how to do this. If I run it as user, it fails to open /var/log/owntone.log. If I sudo -u owntone it fails to open [2022-01-16 13:52:34] [  LOG]     main: Error opening pidfile (/var/run/owntone.pid): Permission denied
sudo ./src/owntone of course works.

Doing that seemed to cause a database rebuild. The "Weird Al" issue is gone. But I still have Trying RSP queries.

[2022-01-16 14:06:06] [DEBUG]      rsp: RSP request: '/rsp/db/0/album?query=artist%3D%22%5C%22Weird%20Al%5C%22%20Yankovic%22&type=browse'
[2022-01-16 14:06:06] [DEBUG]      rsp: Trying RSP query -album_artist="\"Weird Al\" Yankovic"-
[2022-01-16 14:06:06] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM (SELECT f.album, f.album_sort FROM files f WHERE f.disabled = 0 AND (f.album_artist = '"Weird Al" Yankovic') AND f.data_kind = 0 AND f.album != '' GROUP BY f.album_sort, f.album);'

**Comment by frankusb** [comment]
It's my weak git-fu. I do not have the branch checked out.

**Comment by frankusb** [comment]
OK, after installing flex and bison, don't forget to update INSTALL.md, I can't find any problems. Sorry for the false results. I don't use git all that often and I don't understand why 'git branch' does not get me where I want. I just did another checkout of the branch.

**Pull request merged**
