### PR TITLE
Replace libspotify with own implementation mk2

### PR DESCRIPTION
**Pull request by ejurgensen**
@chme, this is my next attempt at replacing libspotify. I think it is now quite close to the goal, but still needs a few things. It has the following improvements over PR #1230:
- It includes your solution for logging in with the web api token (slightly modified).
- It should now be able to play podcasts. With the Spotify url you shared I was able to identify and fix the issue, or at least I hope so.
- It has build switches for the new implementation (--disable-spotify) and the previous one (--enable-libspotify). As you can see I'm planning on enabling the new stuff by default. If built with both enabled, or just with libspotify, then there is a new "use_libspotify" setting in the config.
- I have also renamed the new stuff to "librespot-c" to hopefully join that family later. I have also done some work to make it more of a real library. The latter required some changes to the build process.

I'm not super happy with the changes to the build, I think it is somewhat ugly. I also have little experience with autoconf/make, especially for libraries. If you can see some cleaner ways of doing this please let me know. One thing I am thinking is to move all embedded libraries -  also those without autotools, like evrtsp - into a /libs folder. But probably better to do that separately later.

I still need to do more testing, squash commits, reduce debug logging and probably fix bugs.

### CODE REVIEW

**Comment by bverhagen** [comment]
Hi @ejurgensen ,

Sorry that it took me a while to get back to you.

First of all: the version I was testing earlier worked rather flawlessly! I found one minor bug when queueing, where the message said that '0 tracks' were queued. The track was effectively queued though, so this is just a problem with the notification. Queueing non-spotify tracks do give the correct notification.


With this new branch, I have a problem authenticating against spotify: the spotify authentication callback gives me web page saying:

    Error constructing message to Spotify

The log shows:

     [2021-05-26 11:49:43] [  LOG]      web: OAuth request: '/oauth/spotify?code=<oauth_token>'
     [2021-05-26 11:49:43] [DEBUG]  spotify: Received OAuth code: <oauth_token>
     [2021-05-26 11:49:43] [DEBUG]     http: Parameters in request are: grant_type=authorization_code&code=<oauth_token>&client_id=<id>&client_secret=<secret>&redirect_uri=http%3A%2F%2Fowntone.local%3A3689%2Foauth%2Fspotify
    [2021-05-26 11:49:43] [ INFO]     http: Making request for https://accounts.spotify.com/api/token
    [2021-05-26 11:49:44] [DEBUG]  spotify: Token reply: {"access_token":"<oauth_token>","token_type":"Bearer","expires_in":3600,"refresh_token":"<refresh_token>","scope":"playlist-read-private playlist-read-collaborative streaming user-library-read user-read-private"}
    [2021-05-26 11:49:44] [DEBUG]       db: Running query 'INSERT OR REPLACE INTO admin (key, value) VALUES ('spotify_refresh_token', '<refresh_token>');'
    [2021-05-26 11:49:44] [DEBUG]  spotify: Request Spotify API endpoint: 'https://api.spotify.com/v1/me')
    [2021-05-26 11:49:44] [ INFO]     http: Making request for https://api.spotify.com/v1/me
    [2021-05-26 11:49:44] [DEBUG]  spotify: Spotify API endpoint request: 'https://api.spotify.com/v1/me'
    [2021-05-26 11:49:44] [DEBUG]  spotify: User '<user>', country '<country code>'
    [2021-05-26 11:49:44] [ INFO]     http: Making request for https://APResolve.spotify.com/
    [2021-05-26 11:49:44] [DEBUG]     misc: Connecting to 'spotify' at gew1-accesspoint-b-995x.ap.spotify.com (port 443)
    [2021-05-26 11:49:44] [DEBUG]  spotify: Sent pkt type 1 (cmd=0x00) with size 151 (fd=82)
    [2021-05-26 11:49:44] [DEBUG]  spotify: >>> msg_next >>>
    [2021-05-26 11:49:44] [DEBUG]  spotify: Sent pkt type 2 (cmd=0x00) with size 36 (fd=82)
    [2021-05-26 11:49:44] [DEBUG]  spotify: >>> msg_next >>>
    [2021-05-26 11:49:44] [DEBUG]  spotify: Session error: -2
    [2021-05-26 11:49:44] [DEBUG]     main: Command has 0 pending events
    [2021-05-26 11:49:44] [  LOG]      web: Could not parse Spotify OAuth callback: '/oauth/spotify?code=<oauth_token>'

Which seems to indicate to that the authentication at Spotify was successful and that there is a problem handling the callback from Spotify.

After refreshing the page, it appears that I was successfully authenticated, as the settings page now shows my user id. Playing a Spotify song though fails with:

    [2021-05-26 11:56:11] [DEBUG]   player: Opening track: 'spotify:track:<track>' (id=155, seek=0)
    [2021-05-26 11:56:11] [DEBUG]   player: Setting up input item 'spotify:track:<track>' (item id 155)
    [2021-05-26 11:56:11] [DEBUG]  spotify: setup()
    [2021-05-26 11:56:11] [  LOG]  spotify: Eror opening source: Cannot open media, session is invalid
    [2021-05-26 11:56:11] [DEBUG]  spotify: stop()

**Comment by ejurgensen** [comment]
Thanks a lot for testing. That authentication error doesn't look good - I hope I can reproduce. Will get back to you if I need further help on that.

The error you mention about "0 tracks" should be fixed in master, so when I rebase the PR it should hopefully also be fixed here.

**Comment by ejurgensen** [comment]
Luckily I could reproduce the error, and it was an easy fix. I have also rebased so the other error should also be gone now. Hope you can test again. I will aim for merging beginning of next week unless there are issues or remarks.

**Comment by bverhagen** [comment]
I tested your new version and it is indeed fixed! I will test it further over a longer period of time.

Thx @ejurgensen !

**Comment by ejurgensen** [comment]
I have now merged this into master, although not this PR/branch, but from another one with some small adjustments + doc updates. Hope it works. I also hope you will add the web API scanner support for podcasts, @chme.

**Pull request closed without merging**
