### PR TITLE
[db,ffmpeg] calculate and persist `audio hash` on local files

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Contributing to fixing #85 

* DB - new `audio_hash` column
* scanner - optionally calc audio hash for files  (based on all packets in file)
* json api, conf, smartpl - supporting work

### CODE REVIEW

**Comment by ejurgensen** [comment]
Thanks for the suggestion @whatdoineed2do. It's not great to solve usability issues with config options, but sometimes its all there is to do. Not sure where this is on that scale. In your experience, by what factor does this slow the scanning?

**Comment by whatdoineed2do** [comment]
just ran ths off my laptop with an NVEM drive.

**1198** real audio files locally, destroyed the db on each run, `filescan_disable = true` for startup, and manually trigger the scan via `curl -XPUT http://localhost:3689/api/rescan`

* no audio generation:  3 secs (0.001 per file)
* audio generation: 53 sec (0.044 per file)

I guess this is not a surprise, as the server needs to read most/all of each file in chunks (packet-by-packet).

**Comment by ejurgensen** [comment]
> destroyed the db on each run

How so?

**Comment by whatdoineed2do** [comment]
Destroyed db - I mean deleted the db file before each test

**Comment by ejurgensen** [comment]
I think the existing `avformat_find_stream_info()` reads some kB of each file, have you checked if you can get a hash from that?

**Comment by whatdoineed2do** [comment]
Not seen anything on the existing metadata that the `libav*` maintains.

**Comment by ejurgensen** [comment]
Sorry, but I'm not in favour of this option, so I will close the PR. The reasons are because of the performance impact and the "fix-with-a-config-option" approach.

**Pull request closed without merging**
