### PR TITLE
Fix potential Null pointer dereference in mpd.c

### PR DESCRIPTION
**Pull request by icy17**

### CODE REVIEW

**Comment by ejurgensen** [comment]
I'm not sure checking for OOM is worth it in all cases, so I won't merge this

**Comment by icy17** [comment]
> I'm not sure checking for OOM is worth it in all cases, so I won't merge this

But if OOM, the NULL parameter for bufferevent_setcb and bufferevent_free will lead to a null pointer dereference.  Don't check making the crash hard to trace.

**Comment by ejurgensen** [comment]
It's a bit of a long explenation, and there are differing viewpoints on the subject. The gist of it is that checking for null is not really a reliable solution. If you google Linux memory allocation you can probably find some discussions.

**Comment by icy17** [comment]
Thanks for the explanation, I get it.

**Pull request closed without merging**
