### PR TITLE
Improve behaviour of sliders

### PR DESCRIPTION
**Pull request by ben-willmore**
The progress slider is hard (for me) to use because it gets auto-updated once per second. For me, a typical drag takes a few seconds, and so the auto-updates happen when I am mid-drag, and it gets very frustrating. This PR fixes this by pausing the slider auto-update while a drag is happening. Although it works fairly well, it does this in a somewhat hacky way. If necessary, I would be happy to work on a more robust solution, if you or @chme has a suggestion how to do that.

The PR also increases the slider handle size on mobile, as I find these to be too small for a finger target.

### CODE REVIEW

**Comment by chme** [comment]
I always click / tap at the slider and therefor never noticed this behavior. I tried it now and yes, trying to drag the slider is very frustrating :-)

The implementation looks very hacky ... Did you check if we can use the events the slider emits (<https://github.com/vueform/slider#events>)?
A "cleaner" solution would be, if we get events when dragging the slider starts and ends. We could then stop updating v-model between those two events.

**Comment by ben-willmore** [comment]
The straightforward approach (pause on @update, unpause on @change) doesn't work for two reasons. First, @update is received both during drags and when the progress bar is updated programmatically, and does not reliably indicate a drag has started. Second, @update is received when a drag ends, and may come after the final @change produced by a drag.

In the current version, I simplified the code quite a lot by recording the times when @update is received, and only updating the progress bar if the last @update was more than 900ms ago. This mostly works; however, if you initiate a drag and then hold the cursor still for more than ~1 second, the auto-update will shift the progress bar, as it did before.

I also removed the tick-tock idea where the progress bar only updates every second tick. I often find it is hard to grab the handle in the first place, and I think this is because an auto-update occurs right at the beginning of the drag. Reducing the auto-updates seems to help significantly with this, but it is not a great solution.

**Comment by chme** [comment]
I have opened a pull request for `@vueform/slider` that adds `start` and `end` events: https://github.com/vueform/slider/pull/51

With that change and the following diff, I had no issues dragging the slider any more:

``` diff
diff --git a/web-src/src/pages/PageNowPlaying.vue b/web-src/src/pages/PageNowPlaying.vue
index bb7b60a80..04e0e98e0 100644
--- a/web-src/src/pages/PageNowPlaying.vue
+++ b/web-src/src/pages/PageNowPlaying.vue
@@ -14,6 +14,7 @@
         <div class="container has-text-centered">
           <p class="control has-text-centered fd-progress-now-playing">
             <Slider
+              ref="slider"
               v-model="item_progress_ms"
               :min="0"
               :max="state.item_length_ms"
@@ -22,6 +23,8 @@
               :disabled="state.state === 'stop'"
               :classes="{ target: 'seek-slider' }"
               @change="seek"
+              @start="start_dragging"
+              @end="end_dragging"
             />
             <!--range-slider
               class="seek-slider fd-has-action"
@@ -101,6 +104,7 @@ export default {
     return {
       item_progress_ms: 0,
       interval_id: 0,
+      is_dragged: false,
 
       show_details_modal: false,
       selected_item: {}
@@ -157,6 +161,10 @@ export default {
     }
   },
 
+  mounted: function () {
+    console.log(this.$refs.slider)
+  },
+
   created() {
     this.item_progress_ms = this.state.item_progress_ms
     webapi.player_status().then(({ data }) => {
@@ -176,7 +184,19 @@ export default {
 
   methods: {
     tick: function () {
-      this.item_progress_ms += 1000
+      if (!this.is_dragged) {
+        this.item_progress_ms += 1000
+      }
+    },
+
+    start_dragging: function () {
+      console.log('@start')
+      this.is_dragged = true
+    },
+
+    end_dragging: function () {
+      console.log('@end')
+      this.is_dragged = false
     },
 
     seek: function (newPosition) {
```

**Comment by chme** [comment]
@ben-willmore I have added commit https://github.com/owntone/owntone-server/pull/1441/commits/76297e7ad942654b457a23d4cd46c1218320429a to https://github.com/chme/forked-daapd/tree/web/next

This commit uses my fork of `@vueform/slider` that adds the start and end event (hopefully only temporarily until there is a solution upstream available).
In my tests it worked great. I would appreciate it, if you could test this version.

**Comment by ben-willmore** [comment]
Cool! This is clearly a much cleaner solution, and it seems to work well from some light testing. I can still induce glitches if I try (e.g. by dragging a second time before the seek is complete) but I'm not sure if these will arise in normal use. I'll install it on my main music player and see how I get on.

By the way, this didn't seem to work for me (in `package.json`):
```
    "@vueform/slider": "github:chme/slider#feat/events-start-end-dist",
```

I replaced it with:
```
    "@vueform/slider": "github:chme/slider#faff83ed8a77f2cdbcb7252505ef734301efd139",
```

**Comment by chme** [comment]
I have merged the slider change to master with #1441

**Pull request closed without merging**
