### PR TITLE
[web-src| Optionally Show FilePath on Now playing-Page

### PR DESCRIPTION
**Pull request by LordMyschkin**
I have large parts of my library organized rather by filepath than by albums, so i find it handy to show the filepath on the "now playing"-Page for being able to identify the file played.

Since this may be unintended for other people, I included a setting for this to hide/show the filepath (in all the languages).

### CODE REVIEW

**Comment by ejurgensen** [comment]
Sorry for not replying to this before now. I think the change is fine, but it is a slightly larger web ui change, and I'm not sure how to deal with them since chme is gone. I will think some more about it, and then probably yank it in.

**Comment by LordMyschkin** [comment]
Don't worry, maybe It's of larger importance for me than for anyone else - if there's no use for this change for anyone else, I'm completely fine with not merging.

**Comment by LordMyschkin** [comment]
I hope it all works out - git is still very obscure for me, so i used the functions in visual studio code, but do not really have an idea how they work...

**Comment by ejurgensen** [comment]
Thanks, looks good. I think 2.0.1 as a new version will do fine. With regard to git, you can come a long way just with `git pull`, `git checkout`, `git push` and `git commit`, so you can google those if you want to learn it.

> I'll miss the last one, the blank line in SettingsPageWebinterface.vue - in my opinion, it improved readabilty.

The reason I asked for it to be removed is that it is most likely not the right way to do. Usually, content, logic and design should be separated. However, I don't know much about vue, so I don't know what the right way is. I would guess that it is some sort of markup indicating that the setting belongs to it's own section.

**Comment by LordMyschkin** [comment]
I wish my understanding of vue would be sufficient to know the right way, but i did merely cut-and-paste. Let's hope someone with true knowledge finds the right solution - I have to confess I share your notion there has to be a correct way to implement that nicer than I did.

**Comment by ejurgensen** [comment]
Thanks for this, I've merged it now, but slightly changed, mostly I don't think the option should be enabled by default. I've also rebased and squashed it into one commit.

**Comment by LordMyschkin** [comment]
I am proud like a little child - my first pull request :-)

**Pull request closed without merging**
