### PR TITLE
[web] Fix for pages displaying improperly due to localization

### PR DESCRIPTION
**Pull request by hacketiwack**
Due to missing "$" sign in front of translation function, the album dialog is not opening.

### CODE REVIEW

**Comment by chme** [comment]
Could you please also check the search page, there are two missing translations for the two buttons to switch from local to Spotify search (only visible if you are using the Spotify integration).

**Comment by hacketiwack** [comment]
There are also translation in the GroupByList.js that should be done for "Today", "Last Week", and "Last Month".
However, I'm not able to understand how to get the translation library accessible in this library.
@chme do you know how to achieve that? Thanks in advance.

**Comment by chme** [comment]
Thanks! I have included the commits from this PR in #1497.

**Comment by chme** [comment]
> There are also translation in the GroupByList.js that should be done for "Today", "Last Week", and "Last Month". However, I'm not able to understand how to get the translation library accessible in this library. @chme do you know how to achieve that?

You can import the i18n object and then use it to get a localized string:

``` javascript
import i18n from '@/i18n'

i18n.global.t('page.spotify.browse.show-more')
```

**Pull request closed without merging**
