### PR TITLE
Main renaming of forked-daapd

### PR DESCRIPTION
**Pull request by ejurgensen**
@chme here I have gone through most of the code + docs (except the web UI) and renamed. It's a little bit of a delicate change, let me know if there is something here you see issues with.

I have also updated the app settings on spotify.com - it was possible to add owntone-server.local as a callback URL.

### CODE REVIEW

**Comment by chme** [comment]
@ejurgensen Looks good to me! (I will take care of the web ui)

**Comment by cdlenfert** [comment]
@ejurgensen Adding comments from discussions on simplifying binary and cname to simply `owntone` instead of `owntone-server` https://github.com/owntone/owntone-server/issues/1227#issuecomment-823505732

**Comment by ejurgensen** [comment]
Now I have changed the name to owntone instead of owntone-server

**Comment by chme** [comment]
Still looking good :-)

**Pull request merged**
