### PR TITLE
[web] Migration to Vue 3 and Vite

### PR DESCRIPTION
**Pull request by chme**
[Vue 3](https://vuejs.org/) was first [released](https://blog.vuejs.org/posts/vue-3-one-piece.html) last year in September.
And since February 7th Vue 3 is the [new default version](https://blog.vuejs.org/posts/vue-3-as-the-new-default.html).

This MR [migrates](https://v3-migration.vuejs.org/) the OwnTone web interface from Vue 2.6.x to 3.2.x

In addition to that the build toolchain replaces vue-cli (webpack) with  [Vite](https://vitejs.dev/). Main advantage of Vite is its performance (build times as well as dev server start are much faster).
The commands to build the web interface and to run the dev server are unchanged:

```
# Build web interface
npm run build 

# Start the dev server
npm run serve
```

For formatting Vue/JS code I switched to [Prettier](https://prettier.io/). Linting is done with [ESLint](https://eslint.org/).
I followed this guide to set it up: <https://vueschool.io/articles/vuejs-tutorials/eslint-and-prettier-with-vite-and-vue-js-3/>
(The guide also contains information on how to configure VSCode)

```
# Format code
npm run format

# Lint code (and fix errors that can be automatically fixed)
npm run lint
```

There are two **open issues**, I want to solve before merging:

- [x] Performance of showing large lists (mainly the album list) needs to be improved (we used a performance tweak with Vue 2.6, that is now longer working)
- [x] Documentation update 

## Features / fixes

- Improve reconnection handling (https://github.com/chme/forked-daapd/pull/2, https://github.com/chme/forked-daapd/pull/5, thanks to @ben-willmore)
- Fix failure to detect apple-touch-icon.png (https://github.com/chme/forked-daapd/pull/4, thanks to @ben-willmore)
-  Search page: remember whether "library" or "spotify" is selected (https://github.com/chme/forked-daapd/pull/3, thanks to @ben-willmore)

### CODE REVIEW

**Comment by ejurgensen** [comment]
Very promising. I am using the updated web ui now, and haven't found any issues.

**Comment by chme** [comment]
@ejurgensen Thanks for testing! I did some further changes and thanks to @ben-willmore some additional fixes and features are part of this update. I will give this a final test and - if all goes well - will probably merge it tomorrow.

**Comment by ejurgensen** [comment]
Sounds great! Looks like it was a major undertaking. I haven't discovered any issues while testing, so looking forward to the merge.

**Comment by chme** [comment]
In addition to the Vue 3 migration, I went down the rabbit hole of refactoring stuff ... ;-)
Still some places in the web interface code left that could use some love ... maybe in the next update ...

**Pull request merged**
