### PR TITLE
[web] directory modal handling fix

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Partial fix to #1567 1567

### CODE REVIEW

**Comment by LordMyschkin** [comment]
just change webapi/index.js by this file and change the calling functions in components/ModalDialogDirectory.vue acordingly by passing "this" as second argument to queue_expression_add () and  queue_expression_add_next()

should get rid of the "this.$t() ist undefined"

index js
(rename to .js, of course)

**Comment by LordMyschkin** [comment]
You can check all changes in my fork of owntone, I was ready for a pull request wich fixes both errors, but my fix for the type error was a really bad workaround i was not really happy with.

**Comment by LordMyschkin** [comment]
Just filed an own PR with your changes - I have to get used to git anyway.

**Comment by ejurgensen** [comment]
Merged, thanks

**Pull request merged**
