### PR TITLE
[jsonapi] tracks_put_byid accept multiple track ids

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Allow multiple track properties to be updated in single REST call.

### CODE REVIEW

**Comment by ejurgensen** [comment]
The comma separated path looks peculiar to me. I think it is more kosher to provide the input as json, similar to how updating e.g. multiple speakers work.

**Comment by whatdoineed2do** [comment]
There's the current dependancy on accepting single id which will have to remain for backward compat, so we'd have: request of these 2x forms:

* PUT `/api/library/tracks/1234?usermark=1`
* PUT `/api/library/tracks?usermark=1` with object `{ "tracks": [ 1234, 4567 ] }`

Doing it with the json object payload does complicate the implementation a little but i'll add this and get your feedback.  No objections to the REST interface change proposed in # 2 above?

**Comment by whatdoineed2do** [comment]
You mean something like this:
```
{
  "tracks:" [
    { "usermark": 1, "track_ids": [ 1234, ... ] },
    { "play_count": "increment", "track_ids": [ 3456 ] },
    { "rating": 5, "track_ids": [ 3456 ] }
  ]
}
```
Parsing will get a little messy but i'll refactor

**Comment by ejurgensen** [comment]
That's not a track object - I mean this: https://github.com/owntone/owntone-server/blob/master/README_JSON_API.md#track-object

**Comment by whatdoineed2do** [comment]
Passing over array of `track` objects -- or at least `id` + field(s) user wants setting -- and taking the values from the relevant fields (`rating`, `usermark`) will work.

The `play_count` request is a little troublesme since will rquire more of the db to be exposed (currently only incr, reset to 0 or 1 avaiable).  It also seems out of key for user to set a playcount directly.  For `play_count`, when providing a json `track` object, I'd say this should be a no-op, and return 501 (not implemented).

**Comment by ejurgensen** [comment]
Yes, I agree, go for the simple implementation. 'Not implemented' sounds like the right way to handle the special play_count values.

**Comment by whatdoineed2do** [comment]
This works as described.
```
curl -X PUT "http://localhost:3689/api/library/tracks/31?usermark=4&rating=10"
curl -d '{ "tracks": [ { "id": 34, "usermark": 2, "rating": 80 }, { "id": 35, "rating": 20 } ] }' -X PUT http://localhost:3689/api/library/tracks
```

**Comment by whatdoineed2do** [comment]
@ejurgensen any additional thoughts on current impl?  It works as intended and i think its done. thanks

**Pull request closed without merging**
