### PR TITLE
[rcp] bug fix - speaker unselection upon restart / obey volume 

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Two bugs:

- ensure device flag is `selected = 0` to reflect unconnected status (must initiate Soundbridge connection by design)
- sync volume of Soundbridge to last known volume as set by server
trying to fetch volume of soundbridge (which might have changed since last use by server) proving problematic and volume not reflecting correctly on web ui

### CODE REVIEW

**Comment by ejurgensen** [comment]
`device->selected` should normally not be changed by the backend since it means whether [the user selected the device](https://github.com/owntone/owntone-server/blob/master/src/outputs.h#L44).

**Comment by whatdoineed2do** [comment]
> `device->selected` should normally not be changed by the backend since it means whether [the user selected the device](https://github.com/owntone/owntone-server/blob/master/src/outputs.h#L44).

The Roku device is a little odd; it has a VFD display and not very good powersaving (ie VFD stays on and that can burns out); so when the server shuts down, i instruct the Roku to poweroff.  Thus i want it to be unselected automatically (user does not need to unselect speaker on server shutdown).  The _select_ state is stored via `db_speaker_save() uses the `output_device::selected` value.

Without this change, when the server comes back up and thinks that the Roku device is _selected_ - but a seletected Roku means that we've initiated a connection to it and told it to fetch the stream.mp3 from us (acting like a dumb speaker).  Thus, now it means that if you forget to unselect a Roku and the server restarts, the speaker list shows a _selected_ (ie active) Roku but this isnt true - we have to click (to put into unselected) and click again (to initiate connection) to make it really selected.

the Rokus annouce over mDNS so we dont always have the Roku availabe (its been turned off by user wtih remote control or unplugged etc) to force connection when the server restarts.  Thus we will have the ui showing that a Roku is _selected_ / _available_ but really its not there.


How does the chromecast deal with this situation?

**Comment by ejurgensen** [comment]
> so when the server shuts down, i instruct the Roku to poweroff

If you by server mean owntone then it is meant to always run. So it doesn't sound right to make powersaving depend on server shutdown?

> How does the chromecast deal with this situation?

Not sure, but by your description is sounds like it is the state of the device you should be changing. Hence the check for (device)->state >= OUTPUT_STATE_STOPPED in the display macro I linked to.

**Comment by whatdoineed2do** [comment]
based on this discussion, i took a different approach.

The roku device's `selected` status is persisted to db; when/if the device is seen on the network, we make a connection.  This takes care of the issue i described above.

**Comment by ejurgensen** [comment]
With the latest change it looks like you are connecting and creating a playback session just when the speaker appears. Guess I don't quite understand why that is desirable. I'm fine with merging since this is your area, but just want to check that this is actually what you want to do?

**Comment by whatdoineed2do** [comment]
Perhaps i should ask this - you mention that the `outputs` should NOT set `device->selected = 0` directly.  I see that this can also be done via `outputs_device_deselect()` or `player_speaker_disable()`.  Is the expectation that these are also not called by the `outputs` backend?


The issue I'm trying to solve is that if a user does not _deselect_ the Roku/SB device (from webui or REST) then the db stores `selected = 1`.  This is fine unless `owntone` shutdown without user _deselect_'ing the Roku/SB (lets say user restarts the server because of a pkg upgrade)

When `owntone` is up again, but not playing anything yet, and sees the Roku/SB, the webui shows it as _selected_ (since db `selected = 1`).

BUT this should mean there is an active connection with the Roku/SB (ie streaming data if playoing).  Setting the `device->state = OUTPUT_STATE_STOPPED` before the call to `player_device_add()` isn't reflected in the device (`outputs_device_add()`)  and thus the web ui still shows the device as _selected_.

So I had 2 options in `rcp_mdns_device_cb()`:
* make the connection status of discovered/appeared Roku/SB align with what the UI/server believes (ie force the connection because server is told from db `selected = 1`)
* OR instead, after `player_device_add()` call `player_device_disable()` to force the device as _unselected_ to reflect reality in the webui 
 
I chose the the former based on your comment before that `outputs` should not _unselect_ themselves.

**Comment by ejurgensen** [comment]
> Is the expectation that these are also not called by the outputs backend?

Yes. The idea is that "selected" holds the _user_ choice. As you have seen, it is persisted in the db if the server is restarted.

> This is fine unless owntone shutdown without user deselect'ing the Roku/SB (lets say user restarts the server because of a pkg upgrade). When owntone is up again, but not playing anything yet, and sees the Roku/SB, the webui shows it as selected (since db selected = 1). 

I don't quite understand the issue with this. For other output types this is desired behaviour. Since you bring it up as an issue I suppose there most be something different about Roku, but I didn't get what that is.

> BUT this should mean there is an active connection with the Roku/SB (ie streaming data if playoing)

"selected" doesn't necessarily mean there is a connection. It just means one will be made when playback is started.

**Comment by whatdoineed2do** [comment]
Thanks for that insight.  I had misunderstood what it meant to be _selected_ so was trying to ensure a connection when this was the case.

The change here is relatively simple now - we let `probe` take care of re-establishing connection and a copy/paste bug in `device_flush` that was always setting `state` to stopped.

This should be good to merge pending any final review from yourself

**Pull request merged**
