### PR TITLE
Switch to MkDocs for documentation

### PR DESCRIPTION
**Pull request by chme**
Instead of only having single README markdown files to document forked-daapd usage/setup/... this PR introduces [MkDocs](https://www.mkdocs.org/) with the [Material theme](https://squidfunk.github.io/mkdocs-material/) to generate the documentation. MkDocs is a static site generator that takes markdown files and converts them to HTML.

Advantages are:

- Search functionality
- Responsive design
- Easier to navigate
- Some nice [markdown extensions](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/) that make the documentation visually more appealing

The generated documentation can be deployed via GitHub pages. From this PR's branch it is e. g. deployed to https://chme.github.io/forked-daapd/

All READMEs should have been ported to MkDocs. I also updated the main [README.md](https://github.com/chme/forked-daapd/blob/mkdocs-material/README.md).

This PR superseeds #1172. Instead of restructuring the documentation in smaller pages, like #1172 did, this PR keeps the existing readme files (only light formatting changes are done), renames them and moved them into the docs folder.
I think, it would be good to restructure the documentation to make it easier to read/understand, but this should be done in followup steps.

### CODE REVIEW

**Comment by ejurgensen** [comment]
This is an excellent improvement. The start page with the icons, screenshots, search box and index is a big step forward.

I agree that the structure needs improvement. I think it would be good if that could be included in the PR, otherwise we would be taking a step backwards on that part. The current README_xxx's are meant to be extensions to the main README on specialised subjects, but with this change they become main headings in the index to the left. I'm not so fond of that. I think the main index should be closer to the current index of README.md.

**Comment by chme** [comment]
@ejurgensen I split the documentation into several pages. Is this closer to what you have in mind: https://chme.github.io/forked-daapd/ (there are some broken links in text, will fix it, if it is the right direction)?

**Comment by ejurgensen** [comment]
That looks great! I think that structure is spot on.

**Comment by chme** [comment]
@ejurgensen great! I moved the documentation files a bit to keep all docs related files in the `docs` folder. If it is OK for you, I would merge this soon (rebasing it is a pain ...)

**Comment by ejurgensen** [comment]
I guess I don't like the directory structure in "docs" very much, e.g. "docs/src/documentation". Strange to have src in docs, and of course docs and documentation isn't so nice. Splitting the README is ok, but I'm not so fond of all the subdirs.

The text-based access to the docs is taking a usability hit in favor of being able to serve better via web.

Would it be possible to have the same web menu, but with a more flat directory structure? So that we can just have e.g. docs/installation.md instead of docs/src/documentation/installation.md?

**Comment by chme** [comment]
> Would it be possible to have the same web menu, but with a more flat directory structure? So that we can just have e.g. docs/installation.md instead of docs/src/documentation/installation.md?

Yes, that is possible. I have added a commit that moves most of the files directly under the /docs folder.
Is this better?

**Comment by ejurgensen** [comment]
Looks great, I like this structure much better. How does it work maintainence-wise? I.e. if we want to add a new `some_doc.md`, then what change is required to add it the right place in the menu structure? Might be good to have a note about that somewhere.

**Comment by chme** [comment]
I recommend to take a look at the documentation at https://squidfunk.github.io/mkdocs-material/ 
In the web version of the docs (<https://chme.github.io/forked-daapd/>) you can find a link to that page at the bottom ("Made with Material for MkDocs").

The configuration file to modify to e. g. add a page to the navigation is [mkdocs.yml](https://github.com/chme/forked-daapd/blob/docs/mkdocs/mkdocs.yml).

The section "nav" in that file defines what links are added to the navigation at which level:

```yaml
# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Getting started: getting-started.md
    - Installation: installation.md
    - Library: library.md
    - Artwork: artwork.md
    - Playlists & radio: playlists.md
    - Smart playlists: smart-playlists.md
    - Clients:
      - Supported clients: clients/supported-clients.md
      - Remote: clients/remote.md
```

There are some [navigation config options](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/) in the "theme" section, that control how the nav is rendered (e. g. that the first level of the nav-tree will be displayed as tabs.

I added a small shell script [mkdocs.sh](https://github.com/chme/forked-daapd/blob/docs/mkdocs/mkdocs.sh) to make it easier to run MkDocs locally (only requires docker installed). Running `./mkdocs.sh` will render the docs and start a local dev server. Running `./mkdocs.sh build` will build the documentation and store the output in the `site` directory.

I have added a bit of information into `mkdocs.yml` with the most important links. 
Maybe we can add a new page for contributing / developer infos in a separate PR. That page could then hold information for how to edit / change the documentation.

**Comment by chme** [comment]
@ejurgensen Do you want to see some further changes/additions to this PR? Or is it good to be merged?

**Comment by ejurgensen** [comment]
I think it looks great, you are welcome to merge it!

**Pull request merged**
