### PR TITLE
[web-src][translate] translate webui to zh-cn

### PR DESCRIPTION
**Pull request by VergilGao**
Hi, @ejurgensen  ,I'm translating webui into Chinese Simplified in this PR.
I'll let you know when it's done.

### CODE REVIEW

**Comment by VergilGao** [comment]
Sorry for the lack of progress, I was busy with work the other day

**Comment by ejurgensen** [comment]
Chinese translation would be great, so just wanted to hear how it is coming along?

**Comment by VergilGao** [comment]
I found my old iPhone, and I thought I could refer to Apple's Remote APP for translation. I'm currently working on a project that's approaching a deadline, and when I'm done with it, I'll have time to complete this part of the translation

**Comment by ejurgensen** [comment]
Closing, stale

**Pull request closed without merging**
