### PR TITLE
MPD 0.21

### PR DESCRIPTION
**Pull request by grobian**
Implement features required to bump the announced protocol support to 0.21

### CODE REVIEW

**Comment by grobian** [comment]
I have more of these, but they obviously need to be stacked.  I thought about splitting them like this, but I could also make one branch with all of the changes up to the latest protocol if you prefer?

**Comment by ejurgensen** [comment]
It would be best for me to take them stepwise, since it makes the PRs smaller and easier to review.

**Comment by ejurgensen** [comment]
Btw, do you have a link to a mpd protocol changelog?

**Comment by grobian** [comment]
I use the footnotes from here: https://mpd.readthedocs.io/en/latest/protocol.html#since-0-23 and work my way up (or down) implementing all features per commit, then upping the version.

**Comment by ejurgensen** [comment]
I don't know what "oneshot" is, can you add a comment about why it is ok to just ignore it?

**Comment by grobian** [comment]
https://www.musicpd.org/doc/libmpdclient/status_8h.html#a28b90f20d71ce6d86a73ea129604f5b0a641b15937e63954cf1eebdff9ff77591

single mode means do not advance to the next in playlist, single mode oneshot means play this song, (stop) then disable single mode

because ```The server only allows single-mode in combination with repeat``` it means single mode already wasn't supported, and hence the oneshot variant cannot be supported either.

**Comment by ejurgensen** [comment]
Merged, thanks!

**Pull request merged**
